name: comcrm
proxy:
  backend:
    - comcrm.lndo.site:4000
  database:
    - comcrm-db.lndo.site:5432

services:
  backend:
    type: node:18
    build:
      - npm install
    scanner: false

  database:
    type: postgres
    portforward: 5432
    scanner: false
    creds:
      user: postgres
      password: postgres
      database: main

tooling:
  npm:
    service: backend
    cmd: npm
