name: comcrm
proxy:
  app:
    - comcrm.lndo.site:3000
    - comcrm-prisma.lndo.site:5555
  database:
    - comcrm-db.lndo.site:5432

services:
  app:
    type: node:18
    build:
      - npm install -g bun
      - bun install
    ssl: true
    scanner: false

  database:
    type: postgres
    portforward: 5432
    scanner: false
    creds:
      user: postgres
      password: postgres
      database: main

tooling:
  startdev:
    service: app
    cmd: bun run dev
  bun:
    service: app
    cmd: bun
  bunx:
    service: app
    dir: /app
    cmd: bunx
  prisma:
    service: app
    cmd: bunx prisma
